
development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: IQCloud_Development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database:
  pool: 5
  username:
  password: 
