default:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  database: IQCloud_development
development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  database: IQCloud_development
test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  database: IQCloud_test
production:
  adapter: postgresql
  encoding: unicode
  database: d47c9dn4n5qnv7
  pool: 5
  username: uthowfuewohmja
  password: bwgvHUO3OHyDeBU2YXUaJBow4r