# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2be972ce9d4596ed6fc1497c2407a9f260c23b60ad1d4915f44b0a35eb529f5bd1f72c0ee9e3a505dbf7f186cca0b90ae67d1ea9c84d1b00cf8f6d86347bb0cd

test:
  secret_key_base: a4f7ab0bbe42cf9e73f88e15da1535b8b98238b6ae64753b17b81bc2cd93d978862fdb7ed66fb959894a19e3634e189aed12e0832fd633c8ec6e26e9ee1ad1ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
